service: wedding-app-api

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: "20201221"
  stage: dev
  region: us-east-1

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:GetItem
        - dynamodb:BatchGetItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:Query
        - dynamodb:Scan
        - sns:Publish
      Resource: "*"

functions:
  getEventsInfo:
    handler: api/getEventsInfo.handler
    description: Retrieve the information for all the wedding events
    events:
      - http:
          path: /eventsInformation/{guestCode}
          method: get
          cors: true
  getGuestRSVP:
    handler: api/getGuestRSVP.handler
    description: Retrieve a pre-existing guest RSVP record
    events:
      - http:
          path: /rsvp/{guestId}
          method: get
          cors: true
  createRSVP:
    handler: api/createRSVP.handler
    description: Create a new RSVP entry for a guest
    events:
      - http:
          path: /rsvp
          method: post
          cors: true
  updateRSVP:
    handler: api/updateRSVP.handler
    description: Update existing RSVP record
    events:
      - http:
          path: /rsvp/{guestId}/update
          method: put
          cors: true
  getAllGuests:
    handler: api/getAllGuests.handler
    description: Retrieve all guests
    events:
      - http:
          path: /weddingGuestCount
          method: get
          cors: true
plugins:
  - serverless-offline
